Update patch set 10
Patch Set 10: Verified-1

Removing storage breaks the signout.
TypeError: Storage.removeCredentials is not a function

Patch-set: 10
Reviewer: Gerrit User 1015148 <1015148@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1